print("ab\rcdiff")
print("ab\acdiff")
print("ab\fcdiff")
print("ab\tcdiff")
print("ab\vcdiff")
print("\t\tab\n\t\tcdiff")
print("hfll\\nfjld")
print(r"hfll\nfjld") #raw i mean forward escaping that we used in wake up of NIC.
print("\N{pound sign}")
print("\N{dollar sign}")
print("\N{yen sign}")
print("\N{copyright sign}")
print("\N{latin small letter a}")
print("\N{superscript nine}")
print("\N{subscript nine}")